const List = [
  {
    id: 1,
    name: "Radio1",
    url: "http://icecast.vrtcdn.be/radio1-high.mp3",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/VRT_Radio_1_logo.svg/1200px-VRT_Radio_1_logo.svg.png",
    genre: "nationaal",
  },
  {
    id: 2,
    name: "Radio1 classics",
    url: "http://icecast.vrtcdn.be/radio1_classics-high.mp3",
    logo: "https://cdn-profiles.tunein.com/s309221/images/logod.png?t=158654",
    genre: "klassiek",
  },
  {
    id: 3,
    name: "Radio1 - De Lage Landen Lijst",
    url: "http://icecast.vrtcdn.be/radio1_lagelanden-high.mp3",
    logo: "https://cds.radio1.be/sites/default/files/styles/800x800/public/article/2020_10/lllstreamwebsite-02.png?itok=U7Q2O8iP",
    genre: "nationaal",
  },
  {
    id: 4,
    name: "VRT Radio 2 Bene Bene",
    url: "http://icecast.vrtcdn.be/radio2_benebene-high.mp3",
    logo: "https://cdn-profiles.tunein.com/s309230/images/logog.png?t=1",
    genre: "pop",
  },
  {
    id: 5,
    name: "VRT Radio 2 Antwerpen",
    url: " http://icecast.vrtcdn.be/ra2ant-high.mp3",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/VRT_Radio_2_logo.svg/1200px-VRT_Radio_2_logo.svg.png",
    genre: "pop , rock , regionaal",
  },
  {
    id: 6,
    name: "VRT Radio 2 Limburg",
    url: "http://icecast.vrtcdn.be/ra2lim-high.mp3",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/VRT_Radio_2_logo.svg/1200px-VRT_Radio_2_logo.svg.png",
    genre: "pop , regionaal",
  },
  {
    id: 7,
    name: "VRT Radio 2 Oost-Vlaanderen",
    url: "http://icecast.vrtcdn.be/ra2ovl-high.mp3",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/VRT_Radio_2_logo.svg/1200px-VRT_Radio_2_logo.svg.png",
    genre: "pop , regionaal",
  },
  {
    id: 8,
    name: "VRT Radio 2 Vlaams-Brabant",
    url: "http://icecast.vrtcdn.be/ra2vlb-high.mp3",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/VRT_Radio_2_logo.svg/1200px-VRT_Radio_2_logo.svg.png",
    genre: "pop , regionaal",
  },
  {
    id: 9,
    name: "VRT Klara",
    url: "http://icecast.vrtcdn.be/klara-high.mp3",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/VRT_Klara_logo.svg/1200px-VRT_Klara_logo.svg.png",
    genre: "klassiek",
  },
  {
    id: 10,
    name: "VRT Klara Continuo",
    url: "http://icecast.vrtcdn.be/klaracontinuo-high.mp3",
    logo: "https://www.jecoutelaradioenligne.com/wp-content/uploads/logo-klara-continuo-vrt.jpg",
    genre: "klassiek",
  },
  {
    id: 11,
    name: "VRT Studio Brussel",
    url: "http://icecast.vrtcdn.be/stubru-high.mp3",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/VRT_StuBru_logo.svg/1200px-VRT_StuBru_logo.svg.png",
    genre: "rock , top40",
  },
  {
    id: 12,
    name: "MNM",
    url: "http://icecast.vrtcdn.be/mnm-high.mp3",
    logo: "https://images.squarespace-cdn.com/content/v1/520141b3e4b067924ab14494/1580641590212-Y8LQ8AET4TIBVY9899KK/mnm-logo.png",
    genre: "pop , top40",
  },
  {
    id: 13,
    name: " MNM R&Beats",
    url: "http://icecast.vrtcdn.be/mnm_urb-high.mp3",
    logo: "https://cds.mnm.be/sites/default/files/styles/800x600_focus/public/article/2018_10/logo_roosrood.png?itok=QsXgQVWq",
    genre: "r&b",
  },
  {
    id: 14,
    name: "VRT NWS",
    url: "http://progressive-audio.vrtcdn.be/content/fixed/11_11niws-snip_hi.mp3",
    logo: "",
    genre: "news",
  },
  {
    id: 15,
    name: "VRT Ketnet Hits",
    url: "http://icecast.vrtcdn.be/ketnetradio-high.mp3",
    logo: "",
    genre: "kids",
  },
];

export default List;
